# stages:
#    - build
#    - deploy

# # build stage
# build_testnet:      # This job runs in the deploy stage.
#    image: node:alpine
#    stage: build
#    only:
#       refs:
#         - develop
#    script:
#       - npm install
#       - npm run build
#    cache:
#      paths:
#        - node_modules/
#    artifacts:
#       paths:
#          # build folder
#          - dist/
#       expire_in: 1 hour
#    tags:
#       - binomo-fe-testnet
# # production stage
# deploy_testnet:
#    stage: deploy
# #   before_script:
# #      - mkdir -p ~/.ssh
# #      - echo -e "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
# #      - chmod 600 ~/.ssh/id_rsa
# #      - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
#    script:
#       - rm -rfv ~/apps/binomo-backend/src/public/*
#       - cp -r dist/* ~/apps/binomo-backend/src/public/
#    tags:
#       - binomo-fe-testnet
